# Simple workflow for updating and deploying static content to GitHub Pages
name: Update and Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: scripts/rebuild.sh

      # - run: sqlite3 --version
      #
      # - uses: astral-sh/setup-uv@v7
      #
      # - name: get secrets
      #   run: |
      #     echo "$TELETHON_CONFIG" >tmp/config.txt
      #     echo "$TELETHON_SESSION_SQL_B64" | base64 -d | sqlite3 tmp/session.session
      #   env:
      #     TELETHON_CONFIG: ${{ secrets.TELETHON_CONFIG }}
      #     TELETHON_SESSION_SQL: ${{ secrets.TELETHON_SESSION_SQL }}
      #
      # - run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- data/ | cut -c26-36 | sort -u
      # - run: uv run scripts/comments.py --last 20 --ids `git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- data/ | cut -c26-36 | sort -u`

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - run: gh release delete subs --cleanup-tag --yes
      - run: gh release create subs tmp/subs.*.txt --generate-notes
